name: Module

on:
  release:
    types: [published]

jobs:
  module:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: 'module/pnpm-lock.yaml'
          registry-url: 'https://npm.pkg.github.com'
      - name: Install
        run: pnpm -C module install
      - name: Build
        run: pnpm -C module build
      - name: Publish
        run: cd module/dist && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
